-- Generated by scripts/schema/generate.js from supabase/mysql-model.json. Do not edit by hand.

create table public.affected_populations (
  record_id integer generated by default as identity not null,
  disaster_id integer not null,
  region varchar(200) not null,
  total_affected integer default 0,
  displaced integer default 0,
  injured integer default 0,
  deceased integer default 0,
  missing integer default 0,
  in_shelters integer default 0,
  need_medical integer default 0,
  need_food integer default 0,
  recorded_date timestamptz default now(),
  updated_at timestamptz default now(),
  primary key (record_id)
);

create table public.agencies (
  agency_id integer generated by default as identity not null,
  agency_name varchar(255) not null,
  agency_type text not null check (agency_type in ('Government', 'NGO', 'International', 'Private Sector', 'Military', 'Medical')),
  contact_person varchar(255),
  phone_number varchar(20),
  email varchar(255),
  address text,
  province varchar(100),
  region varchar(100),
  response_capability text,
  activation_time integer,
  status text default 'Active' check (status in ('Active', 'Inactive', 'Suspended')),
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  primary key (agency_id)
);

create table public.agency_activations (
  activation_id integer generated by default as identity not null,
  disaster_id integer not null,
  agency_id integer not null,
  requested_at timestamptz default now(),
  activated_at timestamptz,
  status text default 'Requested' check (status in ('Requested', 'Confirmed', 'Deployed', 'Completed', 'Cancelled')),
  resources_deployed text,
  personnel_deployed integer,
  notes text,
  primary key (activation_id)
);

create table public.agency_mou (
  mou_id integer generated by default as identity not null,
  agency_id integer not null,
  mou_title varchar(255) not null,
  signed_date date,
  expiry_date date,
  document_path varchar(500),
  resources_pledged text,
  terms_and_conditions text,
  status text default 'Active' check (status in ('Active', 'Expired', 'Pending Renewal', 'Cancelled')),
  created_at timestamptz default now(),
  primary key (mou_id)
);

create table public.agency_resources (
  resource_id integer generated by default as identity not null,
  agency_id integer not null,
  resource_type text not null check (resource_type in ('Volunteers', 'Shelter Space', 'Medical Supplies', 'Food', 'Water', 'Transport', 'Equipment', 'Financial', 'Other')),
  resource_name varchar(255) not null,
  quantity integer,
  unit varchar(50),
  availability_status text default 'Available' check (availability_status in ('Available', 'Deployed', 'Reserved', 'Unavailable')),
  deployment_time integer,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  primary key (resource_id)
);

create table public.alerts (
  alert_id integer generated by default as identity not null,
  alert_type text not null check (alert_type in ('Early Warning', 'Evacuation', 'All Clear', 'Supply Request', 'Volunteer Needed', 'Other')),
  severity text not null check (severity in ('Info', 'Warning', 'Critical', 'Emergency')),
  title varchar(200) not null,
  message text not null,
  affected_region varchar(255),
  issued_by varchar(100) not null,
  issued_at timestamptz default now(),
  expires_at timestamptz,
  status text default 'Active' check (status in ('Active', 'Expired', 'Cancelled')),
  disaster_id integer,
  primary key (alert_id)
);

create table public.capacity_alerts (
  alert_id integer generated by default as identity not null,
  disaster_id integer not null,
  alert_type text not null check (alert_type in ('Shelter Shortage', 'Volunteer Shortage', 'Supply Shortage', 'Medical Shortage', 'Transport Shortage')),
  severity text not null check (severity in ('Low', 'Medium', 'High', 'Critical')),
  current_capacity integer,
  required_capacity integer,
  gap integer,
  gap_percentage numeric(5,2),
  recommendations text,
  status text default 'Active' check (status in ('Active', 'Resolved', 'Acknowledged')),
  created_at timestamptz default now(),
  resolved_at timestamptz,
  primary key (alert_id)
);

create table public.damage_assessments (
  assessment_id integer generated by default as identity not null,
  disaster_id integer not null,
  location varchar(255) not null,
  assessment_date timestamptz default now(),
  assessed_by varchar(100) not null,
  structural_damage text default 'None' check (structural_damage in ('None', 'Minor', 'Moderate', 'Severe', 'Destroyed')),
  casualties integer default 0,
  injuries integer default 0,
  displaced_persons integer default 0,
  estimated_cost numeric(15,2),
  description text,
  photos text,
  status text default 'Preliminary' check (status in ('Preliminary', 'Confirmed', 'Final')),
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  primary key (assessment_id)
);

create table public.disasters (
  disaster_id integer generated by default as identity not null,
  disaster_name varchar(200) not null,
  disaster_type text not null check (disaster_type in ('Earthquake', 'Flood', 'Hurricane', 'Wildfire', 'Tsunami', 'Tornado', 'Drought', 'Landslide', 'Volcanic Eruption', 'Industrial Accident', 'Storm', 'Other')),
  severity text not null check (severity in ('Minor', 'Moderate', 'Severe', 'Catastrophic')),
  description text,
  affected_region varchar(255) not null,
  latitude numeric(10,8),
  longitude numeric(11,8),
  start_date timestamptz not null,
  end_date timestamptz,
  status text default 'Active' check (status in ('Active', 'Contained', 'Recovery', 'Closed')),
  estimated_affected_population integer default 0,
  estimated_damage numeric(15,2),
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  response_tier text default 'Tier 1 - Local' check (response_tier in ('Tier 1 - Local', 'Tier 2 - Regional', 'Tier 3 - National', 'Tier 4 - International')),
  escalation_history text,
  command_center varchar(255),
  primary key (disaster_id)
);

create table public.disaster_shelters (
  id integer generated by default as identity not null,
  disaster_id integer not null,
  shelter_id integer not null,
  activated_at timestamptz default now(),
  deactivated_at timestamptz,
  peak_occupancy integer default 0,
  primary key (id),
  unique (disaster_id, shelter_id)
);

create table public.facility_activations (
  activation_id integer generated by default as identity not null,
  facility_id integer not null,
  disaster_id integer not null,
  activation_date timestamptz default now(),
  deactivation_date timestamptz,
  activation_tier text not null check (activation_tier in ('Tier 1 - Local', 'Tier 2 - Regional', 'Tier 3 - National')),
  current_occupancy integer default 0,
  resources_deployed text,
  activation_status text default 'Active' check (activation_status in ('Requested', 'Active', 'Standby', 'Deactivated')),
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  primary key (activation_id)
);

create table public.host_families (
  host_family_id integer generated by default as identity not null,
  family_name varchar(255) not null,
  contact_person varchar(255) not null,
  phone_number varchar(20) not null,
  email varchar(255),
  address text not null,
  province varchar(100),
  district varchar(100),
  max_guests integer not null,
  current_guests integer default 0,
  preferred_guest_type varchar(255),
  languages_spoken varchar(255),
  amenities text,
  background_check_status text default 'Pending' check (background_check_status in ('Pending', 'Verified', 'Rejected')),
  verified_date date,
  status text default 'Active' check (status in ('Active', 'Inactive', 'Full', 'Suspended')),
  rating numeric(3,2),
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  primary key (host_family_id)
);

create table public.partner_facilities (
  facility_id integer generated by default as identity not null,
  facility_name varchar(255) not null,
  facility_type text not null check (facility_type in ('School', 'University', 'Temple', 'Hotel', 'Community Center', 'Sports Complex', 'Government Building', 'Other')),
  partner_agency_id integer,
  address text not null,
  province varchar(100),
  region varchar(100),
  latitude numeric(10,8),
  longitude numeric(11,8),
  max_capacity integer not null,
  activation_agreement boolean default false,
  activation_time integer,
  contact_person varchar(255),
  phone_number varchar(20),
  amenities text,
  status text default 'Available' check (status in ('Available', 'Activated', 'Unavailable', 'Under Maintenance')),
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  primary key (facility_id)
);

create table public.recovery_projects (
  project_id integer generated by default as identity not null,
  disaster_id integer not null,
  project_name varchar(200) not null,
  project_type text not null check (project_type in ('Infrastructure', 'Housing', 'Healthcare', 'Education', 'Livelihood', 'Community Services', 'Other')),
  description text,
  location varchar(255) not null,
  budget numeric(15,2),
  funding_source varchar(200),
  start_date date,
  expected_end_date date,
  actual_end_date date,
  status text default 'Planned' check (status in ('Planned', 'In Progress', 'Completed', 'On Hold', 'Cancelled')),
  project_manager varchar(100),
  beneficiaries integer default 0,
  progress_percentage integer default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  primary key (project_id)
);

create table public.recruitment_campaigns (
  campaign_id integer generated by default as identity not null,
  campaign_name varchar(255) not null,
  disaster_id integer,
  target_volunteers integer,
  required_skills text,
  start_date date not null,
  end_date date,
  status text default 'Active' check (status in ('Active', 'Completed', 'Cancelled')),
  volunteers_recruited integer default 0,
  description text,
  created_at timestamptz default now(),
  primary key (campaign_id)
);

create table public.relief_supplies (
  supply_id integer generated by default as identity not null,
  supply_name varchar(200) not null,
  category text not null check (category in ('Food', 'Water', 'Medical', 'Clothing', 'Blankets', 'Shelter Materials', 'Hygiene Kits', 'Tools', 'Other')),
  unit varchar(50) not null,
  total_quantity numeric(10,2) default 0.00,
  allocated_quantity numeric(10,2) default 0.00,
  available_quantity numeric(10,2) generated always as ((total_quantity - allocated_quantity)) stored,
  minimum_threshold numeric(10,2) default 0.00,
  storage_location varchar(200),
  expiry_date date,
  status text default 'Available' check (status in ('Available', 'Low Stock', 'Out of Stock', 'Expired')),
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  primary key (supply_id)
);

create table public.resource_requests (
  request_id integer generated by default as identity not null,
  disaster_id integer not null,
  resource_type text not null check (resource_type in ('Volunteers', 'Shelter Space', 'Medical Supplies', 'Food', 'Water', 'Transport', 'Equipment', 'Other')),
  quantity_needed integer not null,
  priority text not null check (priority in ('Low', 'Medium', 'High', 'Critical')),
  requested_by varchar(255),
  required_by timestamptz,
  status text default 'Pending' check (status in ('Pending', 'Approved', 'Fulfilled', 'Partially Fulfilled', 'Cancelled')),
  quantity_fulfilled integer default 0,
  allocated_agencies text,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  primary key (request_id)
);

create table public.response_tier_definitions (
  tier_id integer generated by default as identity not null,
  tier_level integer not null,
  tier_name varchar(100) not null,
  trigger_criteria text not null,
  resources_available text,
  agencies_involved text,
  command_structure text,
  escalation_threshold text,
  description text,
  created_at timestamptz default now(),
  primary key (tier_id),
  unique (tier_level)
);

create table public.shelter_activation_requests (
  request_id integer generated by default as identity not null,
  disaster_id integer not null,
  facility_id integer,
  shelter_id integer,
  requested_at timestamptz default now(),
  activated_at timestamptz,
  expected_capacity integer,
  actual_capacity integer,
  status text default 'Requested' check (status in ('Requested', 'Approved', 'Activated', 'Declined', 'Deactivated')),
  requested_by varchar(255),
  notes text,
  primary key (request_id)
);

create table public.shelters (
  shelter_id integer generated by default as identity not null,
  shelter_name varchar(200) not null,
  shelter_type text not null check (shelter_type in ('Temporary', 'Permanent', 'Evacuation Center', 'Relief Camp', 'Community Center')),
  address varchar(255) not null,
  city varchar(100) not null,
  latitude numeric(10,8),
  longitude numeric(11,8),
  capacity integer not null,
  current_occupancy integer default 0,
  status text default 'Available' check (status in ('Available', 'Full', 'Closed', 'Under Maintenance')),
  facilities text,
  contact_person varchar(100),
  contact_phone varchar(20),
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  primary key (shelter_id)
);

create table public.skills (
  skill_id integer generated by default as identity not null,
  skill_name varchar(100) not null,
  category text not null check (category in ('Medical', 'Logistics', 'Communication', 'Construction', 'Food Service', 'Translation', 'Technical', 'Administrative', 'Other')),
  description text,
  requires_certification boolean default false,
  created_at timestamptz default now(),
  primary key (skill_id),
  unique (skill_name)
);

create table public.smart_recommendations (
  recommendation_id integer generated by default as identity not null,
  disaster_id integer not null,
  recommendation_type text not null check (recommendation_type in ('Activate Shelter', 'Request Volunteers', 'Contact Agency', 'Escalate Tier', 'Deploy Resources', 'Evacuate Area')),
  priority integer not null,
  recommendation_text text not null,
  action_required text,
  estimated_impact text,
  status text default 'Pending' check (status in ('Pending', 'Implemented', 'Dismissed', 'Deferred')),
  created_at timestamptz default now(),
  implemented_at timestamptz,
  primary key (recommendation_id)
);

create table public.supply_distributions (
  distribution_id integer generated by default as identity not null,
  disaster_id integer,
  shelter_id integer,
  supply_id integer not null,
  quantity numeric(10,2) not null,
  distribution_date timestamptz default now(),
  distributed_by varchar(100),
  received_by varchar(100),
  notes text,
  primary key (distribution_id)
);

create table public.thailand_locations (
  location_id integer generated by default as identity not null,
  location_name varchar(200) not null,
  location_type text not null check (location_type in ('Province', 'District', 'City', 'University', 'Landmark', 'Airport', 'Hospital', 'Government')),
  province varchar(100),
  region text not null check (region in ('Northern', 'Northeastern', 'Central', 'Eastern', 'Western', 'Southern')),
  latitude numeric(10,8) not null,
  longitude numeric(11,8) not null,
  address text,
  postal_code varchar(10),
  population integer,
  is_active boolean default true,
  created_at timestamptz default now(),
  primary key (location_id)
);

create table public.tier_escalations (
  escalation_id integer generated by default as identity not null,
  disaster_id integer not null,
  from_tier varchar(50) not null,
  to_tier varchar(50) not null,
  escalated_at timestamptz default now(),
  escalated_by varchar(255),
  reason text not null,
  auto_escalation boolean default false,
  criteria text,
  primary key (escalation_id)
);

create table public.tier_resource_deployments (
  deployment_id integer generated by default as identity not null,
  disaster_id integer not null,
  tier_level integer not null,
  resource_type varchar(100) not null,
  resource_description text,
  quantity integer,
  deployed_at timestamptz default now(),
  status text default 'Deployed' check (status in ('Deployed', 'Active', 'Withdrawn', 'Completed')),
  primary key (deployment_id)
);

create table public.training_programs (
  training_id integer generated by default as identity not null,
  training_name varchar(255) not null,
  category text not null check (category in ('First Aid', 'Search and Rescue', 'Disaster Management', 'Communication', 'Logistics', 'Leadership', 'Other')),
  duration integer,
  description text,
  certification_valid integer,
  created_at timestamptz default now(),
  primary key (training_id)
);

create table public.user_reports (
  report_id integer generated by default as identity not null,
  user_name varchar(100),
  user_email varchar(100),
  user_phone varchar(20),
  reported_location varchar(255),
  disaster_type text check (disaster_type in ('Flood', 'Earthquake', 'Fire', 'Storm', 'Landslide', 'Tsunami', 'Drought', 'Other')),
  severity text check (severity in ('Minor', 'Moderate', 'Severe', 'Critical')),
  description text,
  reported_at timestamptz default now(),
  status text default 'Pending' check (status in ('Pending', 'Verified', 'Dismissed', 'Escalated')),
  admin_notes text,
  verified_by varchar(100),
  verified_at timestamptz,
  latitude numeric(10,8),
  longitude numeric(11,8),
  primary key (report_id)
);

create table public.volunteer_accounts (
  account_id integer generated by default as identity not null,
  volunteer_id integer not null,
  username varchar(50) not null,
  created_at timestamptz default now(),
  last_login timestamptz,
  is_active boolean default true,
  primary key (account_id),
  unique (username)
);

create table public.volunteer_assignments (
  assignment_id integer generated by default as identity not null,
  volunteer_id integer not null,
  disaster_id integer not null,
  shelter_id integer,
  role varchar(100) not null,
  assigned_date timestamptz default now(),
  completed_date timestamptz,
  hours_worked integer default 0,
  status text default 'Active' check (status in ('Active', 'Completed', 'Cancelled')),
  notes text,
  primary key (assignment_id)
);

create table public.volunteer_availability (
  availability_id integer generated by default as identity not null,
  volunteer_id integer not null,
  available_from date not null,
  available_to date not null,
  days_of_week varchar(50),
  status text default 'Available' check (status in ('Available', 'On Deployment', 'Unavailable', 'On Leave')),
  notes text,
  created_at timestamptz default now(),
  primary key (availability_id)
);

create table public.volunteer_deployments (
  deployment_id integer generated by default as identity not null,
  volunteer_id integer not null,
  disaster_id integer not null,
  deployed_at timestamptz default now(),
  returned_at timestamptz,
  role varchar(100),
  location varchar(255),
  performance_rating integer,
  notes text,
  status text default 'Deployed' check (status in ('Deployed', 'Completed', 'Recalled', 'Unavailable')),
  primary key (deployment_id)
);

create table public.volunteers (
  volunteer_id integer generated by default as identity not null,
  first_name varchar(100) not null,
  last_name varchar(100) not null,
  email varchar(150),
  phone varchar(20) not null,
  skills text,
  certification varchar(200),
  availability_status text default 'Available' check (availability_status in ('Available', 'Deployed', 'On Leave', 'Inactive')),
  total_hours_contributed integer default 0,
  emergency_contact varchar(100),
  emergency_phone varchar(20),
  joined_date date not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  primary key (volunteer_id),
  unique (email)
);

create table public.volunteer_skills (
  volunteer_id integer not null,
  skill_id integer not null,
  proficiency_level text default 'Intermediate' check (proficiency_level in ('Beginner', 'Intermediate', 'Advanced', 'Expert')),
  certification_number varchar(100),
  certified_date date,
  expiry_date date,
  primary key (volunteer_id, skill_id)
);

create table public.volunteer_training (
  volunteer_id integer not null,
  training_id integer not null,
  completed_date date not null,
  expiry_date date,
  score integer,
  certificate_number varchar(100),
  status text default 'Valid' check (status in ('Valid', 'Expired', 'Pending Renewal')),
  primary key (volunteer_id, training_id, completed_date)
);

alter table public.affected_populations add constraint affectedpopulations_ibfk_1 foreign key (disaster_id) references public.disasters (disaster_id) on delete cascade deferrable initially immediate;
create index affected_populations_disaster_id_idx on public.affected_populations (disaster_id);
create index affected_populations_region_idx on public.affected_populations (region);
create index agencies_agency_type_idx on public.agencies (agency_type);
create index agencies_province_idx on public.agencies (province);
create index agencies_status_idx on public.agencies (status);
alter table public.agency_activations add constraint agencyactivations_ibfk_1 foreign key (disaster_id) references public.disasters (disaster_id) on delete cascade deferrable initially immediate;
alter table public.agency_activations add constraint agencyactivations_ibfk_2 foreign key (agency_id) references public.agencies (agency_id) on delete cascade deferrable initially immediate;
create index agency_activations_agency_id_idx on public.agency_activations (agency_id);
create index agency_activations_disaster_id_idx on public.agency_activations (disaster_id);
create index agency_activations_status_idx on public.agency_activations (status);
alter table public.agency_mou add constraint agencymou_ibfk_1 foreign key (agency_id) references public.agencies (agency_id) on delete cascade deferrable initially immediate;
create index agency_mou_agency_id_idx on public.agency_mou (agency_id);
create index agency_mou_expiry_date_idx on public.agency_mou (expiry_date);
create index agency_mou_status_idx on public.agency_mou (status);
alter table public.agency_resources add constraint agencyresources_ibfk_1 foreign key (agency_id) references public.agencies (agency_id) on delete cascade deferrable initially immediate;
create index agency_resources_agency_id_idx on public.agency_resources (agency_id);
create index agency_resources_availability_status_idx on public.agency_resources (availability_status);
create index agency_resources_resource_type_idx on public.agency_resources (resource_type);
alter table public.alerts add constraint alerts_ibfk_1 foreign key (disaster_id) references public.disasters (disaster_id) on delete set null deferrable initially immediate;
create index alerts_disaster_id_idx on public.alerts (disaster_id);
create index alerts_issued_at_idx on public.alerts (issued_at);
create index alerts_severity_idx on public.alerts (severity);
create index alerts_status_idx on public.alerts (status);
alter table public.capacity_alerts add constraint capacityalerts_ibfk_1 foreign key (disaster_id) references public.disasters (disaster_id) on delete cascade deferrable initially immediate;
create index capacity_alerts_disaster_id_idx on public.capacity_alerts (disaster_id);
create index capacity_alerts_severity_idx on public.capacity_alerts (severity);
create index capacity_alerts_status_idx on public.capacity_alerts (status);
create index capacity_alerts_alert_type_idx on public.capacity_alerts (alert_type);
alter table public.damage_assessments add constraint damageassessments_ibfk_1 foreign key (disaster_id) references public.disasters (disaster_id) on delete cascade deferrable initially immediate;
create index damage_assessments_disaster_id_idx on public.damage_assessments (disaster_id);
create index damage_assessments_status_idx on public.damage_assessments (status);
create index disasters_affected_region_idx on public.disasters (affected_region);
create index disasters_response_tier_idx on public.disasters (response_tier);
create index disasters_severity_idx on public.disasters (severity);
create index disasters_status_idx on public.disasters (status);
create index disasters_disaster_type_idx on public.disasters (disaster_type);
alter table public.disaster_shelters add constraint disastershelters_ibfk_1 foreign key (disaster_id) references public.disasters (disaster_id) on delete cascade deferrable initially immediate;
alter table public.disaster_shelters add constraint disastershelters_ibfk_2 foreign key (shelter_id) references public.shelters (shelter_id) on delete cascade deferrable initially immediate;
create index disaster_shelters_shelter_id_idx on public.disaster_shelters (shelter_id);
alter table public.facility_activations add constraint facilityactivations_ibfk_1 foreign key (facility_id) references public.partner_facilities (facility_id) on delete no action deferrable initially immediate;
alter table public.facility_activations add constraint facilityactivations_ibfk_2 foreign key (disaster_id) references public.disasters (disaster_id) on delete no action deferrable initially immediate;
create index facility_activations_disaster_id_idx on public.facility_activations (disaster_id);
create index facility_activations_facility_id_idx on public.facility_activations (facility_id);
create index facility_activations_activation_status_idx on public.facility_activations (activation_status);
create index host_families_province_idx on public.host_families (province);
create index host_families_status_idx on public.host_families (status);
create index host_families_background_check_status_idx on public.host_families (background_check_status);
alter table public.partner_facilities add constraint partnerfacilities_ibfk_1 foreign key (partner_agency_id) references public.agencies (agency_id) on delete set null deferrable initially immediate;
create index partner_facilities_province_idx on public.partner_facilities (province);
create index partner_facilities_status_idx on public.partner_facilities (status);
create index partner_facilities_facility_type_idx on public.partner_facilities (facility_type);
create index partner_facilities_partner_agency_id_idx on public.partner_facilities (partner_agency_id);
alter table public.recovery_projects add constraint recoveryprojects_ibfk_1 foreign key (disaster_id) references public.disasters (disaster_id) on delete cascade deferrable initially immediate;
create index recovery_projects_disaster_id_idx on public.recovery_projects (disaster_id);
create index recovery_projects_status_idx on public.recovery_projects (status);
create index recovery_projects_project_type_idx on public.recovery_projects (project_type);
alter table public.recruitment_campaigns add constraint recruitmentcampaigns_ibfk_1 foreign key (disaster_id) references public.disasters (disaster_id) on delete set null deferrable initially immediate;
create index recruitment_campaigns_disaster_id_idx on public.recruitment_campaigns (disaster_id);
create index recruitment_campaigns_status_idx on public.recruitment_campaigns (status);
create index relief_supplies_category_idx on public.relief_supplies (category);
create index relief_supplies_status_idx on public.relief_supplies (status);
alter table public.resource_requests add constraint resourcerequests_ibfk_1 foreign key (disaster_id) references public.disasters (disaster_id) on delete cascade deferrable initially immediate;
create index resource_requests_disaster_id_idx on public.resource_requests (disaster_id);
create index resource_requests_priority_idx on public.resource_requests (priority);
create index resource_requests_status_idx on public.resource_requests (status);
create index resource_requests_resource_type_idx on public.resource_requests (resource_type);
alter table public.shelter_activation_requests add constraint shelteractivationrequests_ibfk_1 foreign key (disaster_id) references public.disasters (disaster_id) on delete cascade deferrable initially immediate;
alter table public.shelter_activation_requests add constraint shelteractivationrequests_ibfk_2 foreign key (facility_id) references public.partner_facilities (facility_id) on delete set null deferrable initially immediate;
alter table public.shelter_activation_requests add constraint shelteractivationrequests_ibfk_3 foreign key (shelter_id) references public.shelters (shelter_id) on delete set null deferrable initially immediate;
create index shelter_activation_requests_facility_id_idx on public.shelter_activation_requests (facility_id);
create index shelter_activation_requests_disaster_id_idx on public.shelter_activation_requests (disaster_id);
create index shelter_activation_requests_status_idx on public.shelter_activation_requests (status);
create index shelter_activation_requests_shelter_id_idx on public.shelter_activation_requests (shelter_id);
create index shelters_city_idx on public.shelters (city);
create index shelters_status_idx on public.shelters (status);
alter table public.smart_recommendations add constraint smartrecommendations_ibfk_1 foreign key (disaster_id) references public.disasters (disaster_id) on delete cascade deferrable initially immediate;
create index smart_recommendations_disaster_id_idx on public.smart_recommendations (disaster_id);
create index smart_recommendations_priority_idx on public.smart_recommendations (priority);
create index smart_recommendations_status_idx on public.smart_recommendations (status);
create index smart_recommendations_recommendation_type_idx on public.smart_recommendations (recommendation_type);
alter table public.supply_distributions add constraint supplydistributions_ibfk_1 foreign key (disaster_id) references public.disasters (disaster_id) on delete set null deferrable initially immediate;
alter table public.supply_distributions add constraint supplydistributions_ibfk_2 foreign key (shelter_id) references public.shelters (shelter_id) on delete set null deferrable initially immediate;
alter table public.supply_distributions add constraint supplydistributions_ibfk_3 foreign key (supply_id) references public.relief_supplies (supply_id) on delete cascade deferrable initially immediate;
create index supply_distributions_distribution_date_idx on public.supply_distributions (distribution_date);
create index supply_distributions_disaster_id_idx on public.supply_distributions (disaster_id);
create index supply_distributions_shelter_id_idx on public.supply_distributions (shelter_id);
create index supply_distributions_supply_id_idx on public.supply_distributions (supply_id);
create index thailand_locations_location_name_idx on public.thailand_locations (location_name);
create index thailand_locations_province_idx on public.thailand_locations (province);
create index thailand_locations_region_idx on public.thailand_locations (region);
create index thailand_locations_location_type_idx on public.thailand_locations (location_type);
alter table public.tier_escalations add constraint tierescalations_ibfk_1 foreign key (disaster_id) references public.disasters (disaster_id) on delete cascade deferrable initially immediate;
create index tier_escalations_disaster_id_idx on public.tier_escalations (disaster_id);
create index tier_escalations_to_tier_idx on public.tier_escalations (to_tier);
alter table public.tier_resource_deployments add constraint tierresourcedeployments_ibfk_1 foreign key (disaster_id) references public.disasters (disaster_id) on delete cascade deferrable initially immediate;
create index tier_resource_deployments_disaster_id_idx on public.tier_resource_deployments (disaster_id);
create index tier_resource_deployments_tier_level_idx on public.tier_resource_deployments (tier_level);
create index user_reports_disaster_type_idx on public.user_reports (disaster_type);
create index user_reports_reported_at_idx on public.user_reports (reported_at);
create index user_reports_status_idx on public.user_reports (status);
alter table public.volunteer_accounts add constraint volunteeraccounts_ibfk_1 foreign key (volunteer_id) references public.volunteers (volunteer_id) on delete cascade deferrable initially immediate;
create index volunteer_accounts_username_idx on public.volunteer_accounts (username);
create index volunteer_accounts_volunteer_id_idx on public.volunteer_accounts (volunteer_id);
alter table public.volunteer_assignments add constraint volunteerassignments_ibfk_1 foreign key (volunteer_id) references public.volunteers (volunteer_id) on delete cascade deferrable initially immediate;
alter table public.volunteer_assignments add constraint volunteerassignments_ibfk_2 foreign key (disaster_id) references public.disasters (disaster_id) on delete cascade deferrable initially immediate;
alter table public.volunteer_assignments add constraint volunteerassignments_ibfk_3 foreign key (shelter_id) references public.shelters (shelter_id) on delete set null deferrable initially immediate;
create index volunteer_assignments_disaster_id_idx on public.volunteer_assignments (disaster_id);
create index volunteer_assignments_status_idx on public.volunteer_assignments (status);
create index volunteer_assignments_volunteer_id_idx on public.volunteer_assignments (volunteer_id);
create index volunteer_assignments_shelter_id_idx on public.volunteer_assignments (shelter_id);
alter table public.volunteer_availability add constraint volunteeravailability_ibfk_1 foreign key (volunteer_id) references public.volunteers (volunteer_id) on delete cascade deferrable initially immediate;
create index volunteer_availability_available_from_available_to_idx on public.volunteer_availability (available_from, available_to);
create index volunteer_availability_status_idx on public.volunteer_availability (status);
create index volunteer_availability_volunteer_id_idx on public.volunteer_availability (volunteer_id);
alter table public.volunteer_deployments add constraint volunteerdeployments_ibfk_1 foreign key (volunteer_id) references public.volunteers (volunteer_id) on delete cascade deferrable initially immediate;
alter table public.volunteer_deployments add constraint volunteerdeployments_ibfk_2 foreign key (disaster_id) references public.disasters (disaster_id) on delete cascade deferrable initially immediate;
create index volunteer_deployments_disaster_id_idx on public.volunteer_deployments (disaster_id);
create index volunteer_deployments_status_idx on public.volunteer_deployments (status);
create index volunteer_deployments_volunteer_id_idx on public.volunteer_deployments (volunteer_id);
create index volunteers_last_name_first_name_idx on public.volunteers (last_name, first_name);
create index volunteers_availability_status_idx on public.volunteers (availability_status);
alter table public.volunteer_skills add constraint volunteerskills_ibfk_1 foreign key (volunteer_id) references public.volunteers (volunteer_id) on delete cascade deferrable initially immediate;
alter table public.volunteer_skills add constraint volunteerskills_ibfk_2 foreign key (skill_id) references public.skills (skill_id) on delete cascade deferrable initially immediate;
create index volunteer_skills_proficiency_level_idx on public.volunteer_skills (proficiency_level);
create index volunteer_skills_skill_id_idx on public.volunteer_skills (skill_id);
alter table public.volunteer_training add constraint volunteertraining_ibfk_1 foreign key (volunteer_id) references public.volunteers (volunteer_id) on delete cascade deferrable initially immediate;
alter table public.volunteer_training add constraint volunteertraining_ibfk_2 foreign key (training_id) references public.training_programs (training_id) on delete cascade deferrable initially immediate;
create index volunteer_training_status_idx on public.volunteer_training (status);
create index volunteer_training_volunteer_id_idx on public.volunteer_training (volunteer_id);
create index volunteer_training_training_id_idx on public.volunteer_training (training_id);

create function public.affected_populations_touch() returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;
create trigger affected_populations_touch before update on public.affected_populations for each row execute function public.affected_populations_touch();

alter table public.affected_populations enable row level security;
revoke all on public.affected_populations from anon, authenticated;
create function public.agencies_touch() returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;
create trigger agencies_touch before update on public.agencies for each row execute function public.agencies_touch();

alter table public.agencies enable row level security;
revoke all on public.agencies from anon, authenticated;
alter table public.agency_activations enable row level security;
revoke all on public.agency_activations from anon, authenticated;
alter table public.agency_mou enable row level security;
revoke all on public.agency_mou from anon, authenticated;
create function public.agency_resources_touch() returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;
create trigger agency_resources_touch before update on public.agency_resources for each row execute function public.agency_resources_touch();

alter table public.agency_resources enable row level security;
revoke all on public.agency_resources from anon, authenticated;
alter table public.alerts enable row level security;
revoke all on public.alerts from anon, authenticated;
alter table public.capacity_alerts enable row level security;
revoke all on public.capacity_alerts from anon, authenticated;
create function public.damage_assessments_touch() returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;
create trigger damage_assessments_touch before update on public.damage_assessments for each row execute function public.damage_assessments_touch();

alter table public.damage_assessments enable row level security;
revoke all on public.damage_assessments from anon, authenticated;
create function public.disasters_touch() returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;
create trigger disasters_touch before update on public.disasters for each row execute function public.disasters_touch();

alter table public.disasters enable row level security;
revoke all on public.disasters from anon, authenticated;
alter table public.disaster_shelters enable row level security;
revoke all on public.disaster_shelters from anon, authenticated;
create function public.facility_activations_touch() returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;
create trigger facility_activations_touch before update on public.facility_activations for each row execute function public.facility_activations_touch();

alter table public.facility_activations enable row level security;
revoke all on public.facility_activations from anon, authenticated;
create function public.host_families_touch() returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;
create trigger host_families_touch before update on public.host_families for each row execute function public.host_families_touch();

alter table public.host_families enable row level security;
revoke all on public.host_families from anon, authenticated;
create function public.partner_facilities_touch() returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;
create trigger partner_facilities_touch before update on public.partner_facilities for each row execute function public.partner_facilities_touch();

alter table public.partner_facilities enable row level security;
revoke all on public.partner_facilities from anon, authenticated;
create function public.recovery_projects_touch() returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;
create trigger recovery_projects_touch before update on public.recovery_projects for each row execute function public.recovery_projects_touch();

alter table public.recovery_projects enable row level security;
revoke all on public.recovery_projects from anon, authenticated;
alter table public.recruitment_campaigns enable row level security;
revoke all on public.recruitment_campaigns from anon, authenticated;
create function public.relief_supplies_touch() returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;
create trigger relief_supplies_touch before update on public.relief_supplies for each row execute function public.relief_supplies_touch();

alter table public.relief_supplies enable row level security;
revoke all on public.relief_supplies from anon, authenticated;
create function public.resource_requests_touch() returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;
create trigger resource_requests_touch before update on public.resource_requests for each row execute function public.resource_requests_touch();

alter table public.resource_requests enable row level security;
revoke all on public.resource_requests from anon, authenticated;
alter table public.response_tier_definitions enable row level security;
revoke all on public.response_tier_definitions from anon, authenticated;
alter table public.shelter_activation_requests enable row level security;
revoke all on public.shelter_activation_requests from anon, authenticated;
create function public.shelters_touch() returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;
create trigger shelters_touch before update on public.shelters for each row execute function public.shelters_touch();

alter table public.shelters enable row level security;
revoke all on public.shelters from anon, authenticated;
alter table public.skills enable row level security;
revoke all on public.skills from anon, authenticated;
alter table public.smart_recommendations enable row level security;
revoke all on public.smart_recommendations from anon, authenticated;
alter table public.supply_distributions enable row level security;
revoke all on public.supply_distributions from anon, authenticated;
alter table public.thailand_locations enable row level security;
revoke all on public.thailand_locations from anon, authenticated;
alter table public.tier_escalations enable row level security;
revoke all on public.tier_escalations from anon, authenticated;
alter table public.tier_resource_deployments enable row level security;
revoke all on public.tier_resource_deployments from anon, authenticated;
alter table public.training_programs enable row level security;
revoke all on public.training_programs from anon, authenticated;
alter table public.user_reports enable row level security;
revoke all on public.user_reports from anon, authenticated;
alter table public.volunteer_accounts enable row level security;
revoke all on public.volunteer_accounts from anon, authenticated;
alter table public.volunteer_assignments enable row level security;
revoke all on public.volunteer_assignments from anon, authenticated;
alter table public.volunteer_availability enable row level security;
revoke all on public.volunteer_availability from anon, authenticated;
alter table public.volunteer_deployments enable row level security;
revoke all on public.volunteer_deployments from anon, authenticated;
create function public.volunteers_touch() returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;
create trigger volunteers_touch before update on public.volunteers for each row execute function public.volunteers_touch();

alter table public.volunteers enable row level security;
revoke all on public.volunteers from anon, authenticated;
alter table public.volunteer_skills enable row level security;
revoke all on public.volunteer_skills from anon, authenticated;
alter table public.volunteer_training enable row level security;
revoke all on public.volunteer_training from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;

-- Volunteer logins move to Supabase Auth (spec §4.5). Plain-text passwords are not migrated.
alter table public.volunteer_accounts add column user_id uuid unique references auth.users (id) on delete cascade;

-- Anonymous report rate limiting (spec §4.5). Stores only a salted SHA-256 of the IP.
create table public.report_rate_limits (
  ip_hash text not null,
  created_at timestamptz not null default now()
);
create index report_rate_limits_ip_hash_created_at_idx on public.report_rate_limits (ip_hash, created_at);
alter table public.report_rate_limits enable row level security;
revoke all on public.report_rate_limits from anon, authenticated;
