import { pgTable, toSnake } from './names.js';

const q = (s) => `'${String(s).replace(/'/g, "''")}'`;
const kept = (t, opts) => t.columns.filter((c) => !(opts.dropColumns?.[t.name] ?? []).includes(c.name));

function pgType(c) {
	const len = c.columnType.match(/\((\d+)(?:,(\d+))?\)/);
	switch (c.dataType) {
		case 'int':
		case 'mediumint':
			return 'integer';
		case 'bigint':
			return 'bigint';
		case 'smallint':
			return 'smallint';
		case 'tinyint':
			return c.columnType === 'tinyint(1)' ? 'boolean' : 'smallint';
		case 'varchar':
		case 'char':
			return `varchar(${len[1]})`;
		case 'text':
		case 'mediumtext':
		case 'longtext':
		case 'enum':
			return 'text';
		case 'decimal':
			return `numeric(${len[1]},${len[2] ?? 0})`;
		case 'float':
		case 'double':
			return 'double precision';
		case 'date':
			return 'date';
		case 'datetime':
		case 'timestamp':
			return 'timestamptz';
		case 'json':
			return 'jsonb';
		default:
			throw new Error(`Unsupported MySQL type ${c.dataType} (${c.columnType})`);
	}
}

function pgDefault(c, type) {
	if (c.default === null) return '';
	if (c.default === 'CURRENT_TIMESTAMP') return ' default now()';
	if (type === 'boolean') return ` default ${c.default === '1' ? 'true' : 'false'}`;
	if (/^(integer|bigint|smallint|numeric|double)/.test(type)) return ` default ${c.default}`;
	return ` default ${q(c.default)}`;
}

function columnDdl(c) {
	const name = toSnake(c.name);
	const type = pgType(c);
	if (c.generation) {
		const expr = c.generation.replace(/`(\w+)`/g, (_, n) => toSnake(n));
		return `  ${name} ${type} generated always as (${expr}) stored`;
	}
	let s = `  ${name} ${type}`;
	if (c.extra.includes('auto_increment')) s += ' generated by default as identity';
	else s += pgDefault(c, type);
	if (!c.nullable) s += ' not null';
	if (c.dataType === 'enum') {
		const values = [...c.columnType.matchAll(/'((?:[^']|'')*)'/g)].map((m) => m[1].replace(/''/g, "'"));
		s += ` check (${name} in (${values.map(q).join(', ')}))`;
	}
	return s;
}

export function toPostgres(model, opts = {}) {
	const out = ['-- Generated by scripts/schema/generate.js from supabase/mysql-model.json. Do not edit by hand.', ''];
	for (const t of model.tables) {
		const name = pgTable(t.name);
		const lines = kept(t, opts).map(columnDdl);
		lines.push(`  primary key (${t.primaryKey.map(toSnake).join(', ')})`);
		for (const u of t.uniques) lines.push(`  unique (${u.map(toSnake).join(', ')})`);
		out.push(`create table public.${name} (\n${lines.join(',\n')}\n);`, '');
	}
	for (const t of model.tables) {
		const name = pgTable(t.name);
		for (const fk of t.foreignKeys) {
			out.push(
				`alter table public.${name} add constraint ${fk.name.toLowerCase()} foreign key (${fk.columns.map(toSnake).join(', ')}) references public.${pgTable(fk.refTable)} (${fk.refColumns.map(toSnake).join(', ')}) on delete ${fk.onDelete.toLowerCase()} deferrable initially immediate;`
			);
		}
		for (const ix of t.indexes) {
			const cols = ix.map(toSnake);
			out.push(`create index ${name}_${cols.join('_')}_idx on public.${name} (${cols.join(', ')});`);
		}
	}
	out.push('');
	for (const t of model.tables) {
		const name = pgTable(t.name);
		const touch = kept(t, opts).filter((c) => /on update CURRENT_TIMESTAMP/i.test(c.extra));
		if (touch.length) {
			out.push(
				`create function public.${name}_touch() returns trigger language plpgsql as $$\nbegin\n${touch.map((c) => `  new.${toSnake(c.name)} := now();`).join('\n')}\n  return new;\nend $$;`,
				`create trigger ${name}_touch before update on public.${name} for each row execute function public.${name}_touch();`,
				''
			);
		}
		out.push(`alter table public.${name} enable row level security;`, `revoke all on public.${name} from anon, authenticated;`);
	}
	out.push('revoke all on all sequences in schema public from anon, authenticated;', '');
	return out.join('\n');
}

export function columnMap(model, opts = {}) {
	const map = {};
	for (const t of model.tables) {
		for (const c of kept(t, opts)) {
			const s = toSnake(c.name);
			if (map[s] && map[s] !== c.name) throw new Error(`Column name clash: ${s} ← ${map[s]} / ${c.name}`);
			map[s] = c.name;
		}
	}
	return map;
}
