import { describe, expect, it } from 'vitest';
import { columnMap, toPostgres } from './convert.js';

const col = (o) => ({ nullable: true, default: null, extra: '', generation: '', ...o });
const model = {
	tables: [
		{
			name: 'shelters',
			columns: [
				col({ name: 'ShelterID', dataType: 'int', columnType: 'int', nullable: false, extra: 'auto_increment' }),
				col({ name: 'ShelterName', dataType: 'varchar', columnType: 'varchar(100)', nullable: false }),
				col({ name: 'Status', dataType: 'enum', columnType: "enum('Available','Full','Closed')", default: 'Available' }),
				col({ name: 'Capacity', dataType: 'int', columnType: 'int', default: '0' }),
				col({ name: 'Latitude', dataType: 'decimal', columnType: 'decimal(10,8)' }),
				col({ name: 'IsActive', dataType: 'tinyint', columnType: 'tinyint(1)', default: '1' }),
				col({ name: 'CreatedAt', dataType: 'timestamp', columnType: 'timestamp', default: 'CURRENT_TIMESTAMP', extra: 'DEFAULT_GENERATED' }),
				col({
					name: 'UpdatedAt',
					dataType: 'timestamp',
					columnType: 'timestamp',
					default: 'CURRENT_TIMESTAMP',
					extra: 'DEFAULT_GENERATED on update CURRENT_TIMESTAMP'
				}),
				col({ name: 'Note', dataType: 'text', columnType: 'text', default: "it's" }),
				col({ name: 'Secret', dataType: 'varchar', columnType: 'varchar(255)' })
			],
			primaryKey: ['ShelterID'],
			uniques: [['ShelterName']],
			indexes: [['Status']],
			foreignKeys: []
		},
		{
			name: 'reliefsupplies',
			columns: [
				col({ name: 'SupplyID', dataType: 'int', columnType: 'int', nullable: false, extra: 'auto_increment' }),
				col({ name: 'ShelterID', dataType: 'int', columnType: 'int' }),
				col({ name: 'TotalQuantity', dataType: 'decimal', columnType: 'decimal(10,2)' }),
				col({ name: 'AllocatedQuantity', dataType: 'decimal', columnType: 'decimal(10,2)' }),
				col({
					name: 'AvailableQuantity',
					dataType: 'decimal',
					columnType: 'decimal(10,2)',
					extra: 'STORED GENERATED',
					generation: '(`TotalQuantity` - `AllocatedQuantity`)'
				})
			],
			primaryKey: ['SupplyID'],
			uniques: [],
			indexes: [],
			foreignKeys: [
				{ name: 'fk_supply_shelter', columns: ['ShelterID'], refTable: 'shelters', refColumns: ['ShelterID'], onDelete: 'SET NULL' }
			]
		}
	]
};
const opts = { dropColumns: { shelters: ['Secret'] } };

describe('toPostgres', () => {
	const ddl = toPostgres(model, opts);
	it('creates snake_case tables with identity keys and mapped types', () => {
		expect(ddl).toContain('create table public.shelters (');
		expect(ddl).toContain('shelter_id integer generated by default as identity not null');
		expect(ddl).toContain('shelter_name varchar(100) not null');
		expect(ddl).toContain('latitude numeric(10,8)');
		expect(ddl).toContain('is_active boolean default true');
		expect(ddl).toContain('capacity integer default 0');
		expect(ddl).toContain('created_at timestamptz default now()');
		expect(ddl).toContain("note text default 'it''s'");
		expect(ddl).toContain('primary key (shelter_id)');
		expect(ddl).toContain('unique (shelter_name)');
	});
	it('turns enums into checks', () => {
		expect(ddl).toContain("status text default 'Available' check (status in ('Available', 'Full', 'Closed'))");
	});
	it('keeps generated columns as stored expressions', () => {
		expect(ddl).toContain(
			'available_quantity numeric(10,2) generated always as ((total_quantity - allocated_quantity)) stored'
		);
	});
	it('adds deferrable foreign keys after all tables', () => {
		const fk = ddl.indexOf('alter table public.relief_supplies add constraint fk_supply_shelter');
		expect(fk).toBeGreaterThan(ddl.indexOf('create table public.relief_supplies'));
		expect(ddl).toContain(
			'foreign key (shelter_id) references public.shelters (shelter_id) on delete set null deferrable initially immediate;'
		);
	});
	it('adds indexes, touch triggers for on-update columns, and locks tables down', () => {
		expect(ddl).toContain('create index shelters_status_idx on public.shelters (status);');
		expect(ddl).toContain('new.updated_at := now();');
		expect(ddl).toContain('create trigger shelters_touch before update on public.shelters');
		expect(ddl).toContain('alter table public.shelters enable row level security;');
		expect(ddl).toContain('revoke all on public.shelters from anon, authenticated;');
	});
	it('drops requested columns', () => {
		expect(ddl).not.toContain('secret');
	});
	it('rejects unknown MySQL types', () => {
		const bad = { tables: [{ ...model.tables[0], columns: [col({ name: 'X', dataType: 'geometry', columnType: 'geometry' })] }] };
		expect(() => toPostgres(bad, {})).toThrow('geometry');
	});
});

describe('columnMap', () => {
	it('maps snake back to the original Pascal names, skipping dropped columns', () => {
		const map = columnMap(model, opts);
		expect(map.shelter_id).toBe('ShelterID');
		expect(map.available_quantity).toBe('AvailableQuantity');
		expect(map.secret).toBeUndefined();
	});
});
