// mysql-model.json → supabase/migrations/0001_init.sql + src/lib/server/column-names.ts
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { columnMap, toPostgres } from './convert.js';

const OPTS = { dropColumns: { volunteeraccounts: ['Password'] } };

const EXTRA = `
-- Volunteer logins move to Supabase Auth (spec §4.5). Plain-text passwords are not migrated.
alter table public.volunteer_accounts add column user_id uuid unique references auth.users (id) on delete cascade;

-- Anonymous report rate limiting (spec §4.5). Stores only a salted SHA-256 of the IP.
create table public.report_rate_limits (
  ip_hash text not null,
  created_at timestamptz not null default now()
);
create index report_rate_limits_ip_hash_created_at_idx on public.report_rate_limits (ip_hash, created_at);
alter table public.report_rate_limits enable row level security;
revoke all on public.report_rate_limits from anon, authenticated;
`;

const model = JSON.parse(await readFile(new URL('../../supabase/mysql-model.json', import.meta.url), 'utf8'));
await mkdir(new URL('../../supabase/migrations/', import.meta.url), { recursive: true });
await writeFile(new URL('../../supabase/migrations/0001_init.sql', import.meta.url), toPostgres(model, OPTS) + EXTRA);

const map = columnMap(model, OPTS);
const ts = `// Generated by scripts/schema/generate.js. Do not edit by hand.\n// snake_case Postgres column → original PascalCase name used in API JSON.\nexport const COLUMN_NAMES: Record<string, string> = ${JSON.stringify(map, null, '\t')};\n`;
await writeFile(new URL('../../src/lib/server/column-names.ts', import.meta.url), ts);
console.log(`0001_init.sql written; ${Object.keys(map).length} column names mapped`);
